In [1]:
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
# Will compare
# - Logistic Regression
# - SVM
# - Random Forest
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [11]:
# Logistic Regression
lr = LogisticRegression(max_iter=10000)
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9685185185185186

In [12]:
# SVM
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [13]:
# Random Forest
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9814814814814815

Everytime you run the code, the score will change due to the change in train,test dataset

In [14]:
# K fold
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
# get_score(LogisticRegression(max_iter=10000),x_train,x_test,y_train,y_test)

In [23]:
from sklearn.model_selection import StratifiedKFold
# this helps dividing it into folds uniformly
folds = StratifiedKFold(n_splits=3)
folds


StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [39]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data,digits.target):
    X_train,X_test,Y_train,Y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,Y_train,Y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))

In [40]:
scores_lr

[0.9265442404006677, 0.9415692821368948, 0.9165275459098498]

In [31]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [33]:
scores_rf

[0.9465776293823038, 0.9599332220367279, 0.9298831385642737]

In [35]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.925     , 0.875     , 0.93871866, 0.93314763, 0.89693593])